// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdYKdES83hOpvPw7a2qnIPuEEgw9djHQY',
    appId: '1:591242324920:web:4ae0e659496d987f543d4d',
    messagingSenderId: '591242324920',
    projectId: 'attendance-project-c8b23',
    authDomain: 'attendance-project-c8b23.firebaseapp.com',
    storageBucket: 'attendance-project-c8b23.appspot.com',
    measurementId: 'G-103397J97T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_IpJilRvTWDM5XZSJHCmio3MahUlMWrY',
    appId: '1:591242324920:android:fdf0d28a207a94d7543d4d',
    messagingSenderId: '591242324920',
    projectId: 'attendance-project-c8b23',
    storageBucket: 'attendance-project-c8b23.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgih9zoAK61jXkDzPyL7renk5hZ4Kbgt4',
    appId: '1:591242324920:ios:0d6f816f96bc7d75543d4d',
    messagingSenderId: '591242324920',
    projectId: 'attendance-project-c8b23',
    storageBucket: 'attendance-project-c8b23.appspot.com',
    iosClientId: '591242324920-l862uv3iq5m734rkev3hkqand8njje76.apps.googleusercontent.com',
    iosBundleId: 'com.example.atendanceProject',
  );
}
